## Configuración inicial

In [2]:
import numpy as np #operaciones numéricas y álgebra lineal

In [ ]:
#Arrays: El bloque fundamental de Numpy
#Un array es simplemente una colección ordenada de números: Todos sus elementos son del mismo tipo.

#Hay 3 sabores según su número de dimensiones:

#Escalar --> Un solo número
#Vector --> Una Fila de números -> [1,2,3,4,5,6]
#Matriz --> Filas/Columnas  -->    [[1,2,3],
#                                   [4,5,6]]

In [5]:
#Array de 1 dimensión : Vector
# Variable.
vector = np.array([3,7,2,9,1])

print("Vector (1D): ", vector)
print("Forma: ", vector.shape) # 5 elementos, 1 dimensión
print("Tipo de dato: ", vector.dtype)

Vector (1D):  [3 7 2 9 1]
Forma:  (5,)
Tipo de dato:  int64


In [9]:
#Matriz: array de 2 dimensiones
#Una Matriz en una tabla de filas y columnas

matriz = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])

print("Matriz (2D):")
print(matriz)
print("Forma: ", matriz.shape)
print("Rango: ", matriz.ndim, "dimensiones")

Matriz (2D):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma:  (3, 3)
Rango:  2 dimensiones


In [16]:
#Operaciones básicas (Vectorizadas)
#Numpy Opera directamente sobre todos los elementos a la vez, sin bucles.

a1 = np.array([10,20,30])
a2 = np.array([1,2,3])

print("Suma a1 + a2 = ", a1 + a2)
print("Resta a1 - a2 = ", a1 - a2)
print("Potencia a1*2 = ", a2 ** 2)
print("Escalar a1*2 = ", a1 * 2) # va a ir multiplicando cada valor del vector x 2

Suma a1 + a2 =  [11 22 33]
Resta a1 - a2 =  [ 9 18 27]
Potencia a1*2 =  [1 4 9]
Escalar a1*2 =  [20 40 60]


# Qué es un Tensor?

In [ ]:
#Tensor: Es un array de numpy que lo diferente es que tiene cualquier númeor de dimensiones.

tensor = np.array([
    [[1,2,3],
     [4,5,6]],
    
    [[7,8,9],
     [10,11,12]]
])

print(tensor)
print(tensor.shape) #Bloques, filas, columnas

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#Tensor 3D
#Simulemos un lote de imagenes.
#Simulamos 4 imagenes en escala de grises de 8 x 8 pixeles

batch_imagenes = np.random.randint(0, 256, size=(4, 8, 8))

print("Tensor de imágenes:")
print(batch_imagenes)

print(f"Forma: {batch_imagenes.shape} ")
print(f"Dimensiones: {batch_imagenes.ndim} ")


Tensor de imágenes:
[[[254  91  68 183 109  39 109  91]
  [187  33 131  79 193  48 151  66]
  [213 181 213   3 108  27 220 202]
  [178 229  62 243  26 195 124 187]
  [ 55 215  54 224 252 227 203  13]
  [202 237 125 251 236  45 158 149]
  [ 49 160  85  17  76 107 196 145]
  [ 74  14 181   4 168 122 124 227]]

 [[105  59  40  91 111 133 117 216]
  [214 250  85  16  21  83 182  50]
  [ 78  15 169 238 252 154 252   7]
  [ 24 111  85 138 210 170 121 222]
  [166   5   3  68  27 101  91 216]
  [  8 164  82 127  58  36 236  64]
  [182  78  74 226 202 250 150 235]
  [142 123  38  62  25 113  45 238]]

 [[116 181 255 241 128 241 172  53]
  [169  56  59 109 145   0  68 224]
  [ 19 165  23 141 163 255 242 112]
  [ 27  68  49  67  92  52  93  73]
  [218  80  67 119 146 188  36 134]
  [217 152 219 167  91 203 152  98]
  [237 222  61 104 142 240 133  67]
  [174 127 253 236 249 195 170 177]]

 [[134  88 167  60 103 254  46 170]
  [208 143 110  30 192 240  73  12]
  [ 12 109  60  67  60 225  72  16]
  

In [36]:
#Acceder a la primera imagen completa.
print(batch_imagenes[3])

[[ 12 240  29 220 106 204  49 201]
 [ 86 111 240 163 121 202  74 131]
 [ 15  31 217 229  18 219  82  51]
 [161 219   2 147 171  78 247 235]
 [248  60  65 137   9 115  29  43]
 [104 234  58 202   6  81  26 170]
 [ 19  25  45  13  92  69  61 203]
 [ 67 223 150  62 229  18  65  22]]


# ALGEBRA LINEAL

## ¿Por qué Algebra Lineal?

In [ ]:
#Es la rama de las matemáticas que estudia los vectores, las matrices y las transformaciones entre ellos.

In [ ]:
#Concepto de multiplicacion de matrices
# para multiplicar matrices las columnas de la priemra debeb coincidir con la cantidad de filas de lal segunda

X = np.array([[2,1,3,0], #edad, ingresos, deuda, hist
             [1,5,2,1],
             [4,3,0,2]])

W = np.array([
    [1,2],
    [0,1],
    [3,1],
    [2,0]
])

result_multi = X @ W

print(result_multi)

#Multiplicar + sumar
(2*1) + (1*0) + (3*3) + (0*2) = 11


[[11  8]
 [ 9  9]
 [ 8 11]]
